# Generated by Django 4.2 on 2023-04-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_cardscollections_cards_cardscollections_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardscollections',
            name='cards',
            field=models.ManyToManyField(db_column='card_id', to='cards.englishcards'),
        ),
    ]
