# Generated by Django 4.2 on 2023-04-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_cardscollections_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcards',
            name='img',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatar'),
        ),
    ]
