# Generated by Django 4.2 on 2023-04-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_englishcards_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishcards',
            name='img',
        ),
        migrations.AddField(
            model_name='cardscollections',
            name='img',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatar'),
        ),
    ]
