# Generated by Django 4.2 on 2023-04-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_englishcards_img_cardscollections_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardscollections',
            name='img',
            field=models.ImageField(default='default_avata1r.jpg', upload_to='avatar'),
        ),
    ]
