# Generated by Django 4.2 on 2023-04-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_cardscollections_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardscollections',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='avatars'),
        ),
    ]
