# Generated by Django 4.2 on 2023-05-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_englishcards_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishcards',
            name='word_usage',
            field=models.TextField(),
        ),
    ]
