# Generated by Django 4.2 on 2023-05-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_alter_englishcards_word_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='englishcards',
            name='img',
            field=models.ImageField(default='golub.png', upload_to='words_image'),
        ),
    ]
