# Generated by Django 4.2 on 2023-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_englishcards_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishcards',
            name='img',
            field=models.ImageField(default='golub.jpg', upload_to='words_image'),
        ),
    ]
