# Generated by Django 4.2.1 on 2023-06-29 17:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0011_alter_englishcards_img"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EnglishCards",
            new_name="Cards",
        ),
        migrations.RenameModel(
            old_name="CardsCollections",
            new_name="Collections",
        ),
        migrations.CreateModel(
            name="CardCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_list",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.collections",
                    ),
                ),
            ],
        ),
    ]
