# Generated by Django 4.2.1 on 2023-06-29 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0012_rename_englishcards_cards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardcollection",
            name="order_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
    ]


