# Generated by Django 4.2.1 on 2023-06-29 18:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0013_alter_cardcollection_order_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="collections",
            name="order_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), null=True, size=None
            ),
        ),
        migrations.DeleteModel(
            name="CardCollection",
        ),
    ]
