# Generated by Django 4.2.1 on 2023-06-29 18:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0014_collections_order_list_delete_cardcollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="order_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), default=[], size=None
            ),
        ),
    ]
