# Generated by Django 4.2.1 on 2023-07-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0016_alter_collections_order_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="img",
            field=models.ImageField(default="1.jpg", upload_to="avatars"),
        ),
    ]
