# Generated by Django 4.2.1 on 2023-07-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0018_alter_cards_english_word_alter_cards_russian_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collections",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
