# Generated by Django 4.2.1 on 2023-12-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_alter_collections_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='img',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
