# Generated by Django 4.2.1 on 2023-12-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='yt_id',
            field=models.CharField(default=1),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_name',
            field=models.CharField(null=True),
        ),
    ]
