# Generated by Django 4.2.1 on 2023-12-24 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0003_videos_yt_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_collection_name', models.CharField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(db_column='video_id', to='tube.videos')),
            ],
        ),
    ]
