# Generated by Django 4.2.1 on 2023-12-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0004_videocollections'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocollections',
            name='img',
            field=models.ImageField(default='1.jpg', upload_to='avatars'),
        ),
    ]
