# Generated by Django 4.2.1 on 2023-12-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0005_videocollections_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocollections',
            name='img',
        ),
        migrations.RemoveField(
            model_name='videocollections',
            name='video_collection_name',
        ),
    ]
