# Generated by Django 4.2.1 on 2023-12-24 09:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tube', '0006_remove_videocollections_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='owner',
        ),
        migrations.DeleteModel(
            name='VideoCollections',
        ),
        migrations.AddField(
            model_name='videos',
            name='owner',
            field=models.ManyToManyField(db_column='owner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
