# Generated by Django 4.2.1 on 2023-12-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0007_remove_videos_owner_delete_videocollections_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_cap',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_subs',
            field=models.FileField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='videos',
            name='vieo_path',
            field=models.FileField(default=1, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_prev',
            field=models.ImageField(default=1, upload_to=''),
        ),
    ]
