# Generated by Django 4.2.1 on 2023-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0008_remove_videos_video_cap_videos_video_subs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='yt_id',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='videos',
            name='yt_url',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
