# Generated by Django 4.2.1 on 2023-12-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0009_alter_videos_video_name_alter_videos_yt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_prev',
            field=models.ImageField(default=1, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_subs',
            field=models.FileField(default=1, max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='videos',
            name='vieo_path',
            field=models.FileField(default=1, max_length=255, upload_to=''),
        ),
    ]
