# Generated by Django 4.2.1 on 2023-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0011_alter_videos_video_prev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_prev',
            field=models.ImageField(default=1, max_length=255, upload_to=''),
        ),
    ]
