# Generated by Django 4.2.1 on 2023-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0012_alter_videos_video_prev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='vieo_path',
            new_name='video_path',
        ),
        migrations.AddField(
            model_name='videos',
            name='video_audi',
            field=models.FileField(default=1, max_length=255, upload_to=''),
        ),
    ]
