# Generated by Django 4.2.1 on 2023-12-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0013_rename_vieo_path_videos_video_path_videos_video_audi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='video_audi',
        ),
    ]
