# Generated by Django 4.2.1 on 2023-07-22 19:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("times", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="times",
            name="verbs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.CharField(), default=tuple, size=None
                ),
                default=tuple,
                size=None,
            ),
        ),
    ]
