# Generated by Django 4.2.1 on 2023-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("times", "0012_verbs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verbs",
            name="time",
        ),
        migrations.AddField(
            model_name="times",
            name="verbs",
            field=models.ManyToManyField(db_column="verbs_id", to="times.verbs"),
        ),
    ]
